Add iehlist.sh to samples
IBM/zoau-samples pull request #50
Opened 2022-11-02 16:57 UTC by lcarcaramo

This is a wrapper for the JCL and volume extraction logic used to run IEHLIST against a data set to get it's directory information.

Usage:
```shell
./iehlist MY.PDS.DATASET
```

2022-11-02 17:01 UTC, MikeFultonDev reviewed
Looks great! Since IEHLIST has a few different verbs, would it make sense to give the script a different name like listpds maybe?

2022-11-02 17:12 UTC, AnthonyGiorgio requested changes

2022-11-02 19:02 UTC, lcarcaramo commented
I renamed `iehlist.sh` to `listdirinfo.sh` and added a copyright statement. Let me know if there are any other issues.

2022-11-03 13:27 UTC, AnthonyGiorgio requested changes

2022-11-03 13:27 UTC, AnthonyGiorgio commented on samples/listdirinfo.sh
> +#!/bin/bash
The double shebang lines here are unorthodox.  I suggest you remove the `/bin/bash` one, as that's not present by default on z/OS.

2022-11-03 14:28 UTC, AnthonyGiorgio approved these changes

2022-11-03 16:25 UTC, MikeFultonDev approved these changes
LGTM - thank you

2023-12-14 03:52 UTC, merged